### ISSUE TITLE
Determine features for ML model

### ISSUE THREAD

**Issue by saphirasnow** [CMU-313/fall-2021-hw4-connect5#2]
Determine which features to use in the ML model

**Comment by thisisalbertliang** [comment]
It seems adding just G2 as a new feature is sufficient for significantly improving the model performance. The f1 score is already improved to 0.9861111111111112 as a result of including G2, so there isn't much room for further improvement.

We also might not want to include too many additional features beyond G2, since an f1 score of 0.9861111111111112 is already an indication of overfitting.
